#ifndef SIMPLEMINER_ERROR_CODES_H
#define	SIMPLEMINER_ERROR_CODES_H

#define SIMPLEMINER_RPC_ERROR_CODE_WRONG_PARAM               -1
#define SIMPLEMINER_RPC_ERROR_CODE_INVALID_SHARE_DATA        -13
#define SIMPLEMINER_RPC_ERROR_CODE_INVALID_JOB_ID            -14
#define SIMPLEMINER_RPC_ERROR_CODE_UNKNOWN_JOB_SHARE         -15
#define SIMPLEMINER_RPC_ERROR_CODE_SLIGHTLY_STALE_SHARE      -16
#define SIMPLEMINER_RPC_ERROR_CODE_REALLY_STALE_SHARE        -17
#define SIMPLEMINER_RPC_ERROR_CODE_DUPLICATE_SHARE           -18
#define SIMPLEMINER_RPC_ERROR_CODE_INVALID_SHARE             -19
#define SIMPLEMINER_RPC_ERROR_CODE_CANT_GET_JOB              -20
#define SIMPLEMINER_RPC_ERROR_CODE_UNKNOWN_WORKER            -21
#define SIMPLEMINER_RPC_ERROR_CODE_UNKNOWN_WORKER_SESSION    -22
#define SIMPLEMINER_RPC_ERROR_CODE_INVALID_WORKER_SESSION_ID -23
#define SIMPLEMINER_RPC_ERROR_CODE_UNKNOWN_ERROR             -24
#define SIMPLEMINER_RPC_ERROR_CODE_WORKER_SESSION_MISMATCH   -25
#define SIMPLEMINER_RPC_ERROR_CODE_DENIED_SHARE              -26

#endif	/* SIMPLEMINER_ERROR_CODES_H */
